---
# ansible配置
# 待管理主机的python命令
ansible_python_interpreter: "/usr/bin/python3"

# k8s集群信息
k8s:
  master_vip: "10.211.55.13"
  master_vport: 8443
  apiservercount: 2
  iface: "enp0s5"
  insecure_registries: '["10.255.1.101"]'
  cluster_ip_range: 10.10.0.0/16
  cluster_dns: 10.10.0.2
  cluster_svc: 10.10.0.1
  cluster_cidr: 172.10.0.0/16
  lb: 
    master1: 10.211.55.11:6443
    master2: 10.211.55.12:6443
# etcd集群配置信息
etcd:
  cluster: "etcd1=https://10.211.55.11:2380,etcd2=https://10.211.55.12:2380,etcd3=https://10.211.55.14:2380"
  servers: "https://10.211.55.11:2379,https://10.211.55.12:2379,https://10.211.55.14:2379"
# TLS证书配置
tls:
  dest:
  - 10.211.55.12
  - 10.211.55.14
# 使用到的镜像，请自行准备可用的镜像
images:
  pause_amd64: "chinaxiang/pause-amd64:3.0"
  calico_node: "calico/node:v3.0.3"
  calico_cni: "calico/cni:v2.0.1"
  calico_kube_controllers: "calico/kube-controllers:v2.0.1"
  coredns: "coredns/coredns:1.1.0"
  heapster_amd64: "chinaxiang/heapster-amd64:v1.5.0"
  kubernetes_dashboard_amd64: "chinaxiang/kubernetes-dashboard-amd64:v1.8.0"
  traefik: "traefik"






