# ansible配置
# 待管理主机的python命令
ansible_python_interpreter: "/usr/bin/python"
# 配置各节点hosts文件
node_hosts:
  - node_ip: 10.211.55.15
    hostname: node1
  - node_ip: 10.211.55.16
    hostname: node2
# k8s集群信息
k8s:
  cli: 10.211.55.15
  master_vip: 10.211.55.15
  master_vport: 6443
  apiservercount: 2
  iface: "eth0"
  insecure_registries: '["192.168.83.123"]'
  cluster_ip_range: 10.10.0.0/16
  cluster_dns: 10.10.0.2
  cluster_svc: 10.10.0.1
  cluster_cidr: 172.10.0.0/16
# etcd集群配置信息
etcd:
  cluster: "etcd1=https://10.211.55.15:2380,etcd2=https://10.211.55.16:2380"
  servers: "https://10.211.55.15:2379,https://10.211.55.16:2379"
# 使用到的镜像，请自行准备可用的镜像
images:
  # pause_amd64: "chinaxiang/pause-amd64:3.0"
  # calico_node: "calico/node:v3.0.3"
  # calico_cni: "calico/cni:v2.0.1"
  # calico_kube_controllers: "calico/kube-controllers:v2.0.1"
  # coredns: "coredns/coredns:1.1.0"
  # heapster_amd64: "chinaxiang/heapster-amd64:v1.5.0"
  # kubernetes_dashboard_amd64: "chinaxiang/kubernetes-dashboard-amd64:v1.8.0"
  # traefik: "traefik"
  pause_amd64: "192.168.83.123/library/pause-amd64:3.0"
  calico_node: "192.168.83.123/library/calico-node:v3.0.3"
  calico_cni: "192.168.83.123/library/calico-cni:v2.0.1"
  calico_kube_controllers: "192.168.83.123/library/calico-kube-controllers:v2.0.1"
  coredns: "192.168.83.123/library/coredns:1.1.0"
  heapster_amd64: "192.168.83.123/library/heapster-amd64:v1.5.0"
  kubernetes_dashboard_amd64: "192.168.83.123/library/kubernetes-dashboard-amd64:v1.8.0"
  traefik: "192.168.83.123/library/traefik"