---
- hosts: "k8s-nodes"
  vars_files:
  - "../config/config.yml"
  tasks:
  - name: "copy files to nodes"
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0755
    with_items:
    - src: "../sbin/kubelet"
      dest: "/usr/bin/"
    - src: "../sbin/kube-proxy"
      dest: "/usr/bin/"
    - src: "../sbin/nsenter"
      dest: "/usr/bin/"
    - src: "template/k8s/kubelet.service"
      dest: "/etc/init/kubelet.conf"
    - src: "template/k8s/kube-proxy.service"
      dest: "/etc/init/kube-proxy.conf"
  - name: "template files to nodes"
    template:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
    with_items:
    - src: "template/k8s/config"
      dest: "/etc/kubernetes/"
    - src: "template/k8s/proxy"
      dest: "/etc/kubernetes/"
    - src: "template/k8s/kubelet"
      dest: "/etc/kubernetes/kubelet"
  - shell: "swapoff -a"
  - block:
    - shell: initctl stop kubelet
      ignore_errors: true 
    - shell: initctl start kubelet
      ignore_errors: true
    - shell: initctl status kubelet
      register: result
    - debug:
        msg: "{{result.stdout}}"
  - block:
    - shell: initctl stop kube-proxy
      ignore_errors: true 
    - shell: initctl start kube-proxy
      ignore_errors: true
    - shell: initctl status kube-proxy
      register: result
    - debug:
        msg: "{{result.stdout}}"
  