---
- hosts: "k8s-nodes"
  vars_files:
  - "../config/config.yml"
  tasks:
  - name: "copy files to all nodes"
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0755
    with_items:
    - src: "../sbin/docker-ce.deb"
      dest: "/opt/"
    - src: "../sbin/libltdl7.deb"
      dest: "/opt/"
    - src: "../sbin/libsystemd-journal0.deb"
      dest: "/opt/"
    - src: "../sbin/conntrack.deb"
      dest: "/opt/"
    - src: "../sbin/libmnl0.deb"
      dest: "/opt/"
    - src: "../sbin/libnetfilter-conntrack3.deb"
      dest: "/opt/"  
  - block:
    - shell: rm -rf /etc/init/docker.conf
    - shell: dpkg -i /opt/libltdl7.deb
    - shell: dpkg -i /opt/libsystemd-journal0.deb
    - shell: dpkg -i /opt/libmnl0.deb
    - shell: dpkg -i /opt/libnetfilter-conntrack3.deb
    - shell: dpkg -i /opt/conntrack.deb
    - shell: dpkg -i /opt/docker-ce.deb
    ignore_errors: true 
  - name: "copy daemon.json to /etc/docker/"
    template:
      src: "template/docker/daemon.json"
      dest: "/etc/docker/"
  - name: "copy docker.service to /etc/init/docker.conf"
    copy:
      src: "template/docker/docker.service"
      dest: "/etc/init/docker.conf"
  - name: "iptables setting"
    shell: "iptables -F && iptables -X \
            && iptables -F -t nat && iptables -X -t nat \
            && iptables -F -t raw && iptables -X -t raw \
            && iptables -F -t mangle && iptables -X -t mangle \
            && iptables -P FORWARD ACCEPT"
  - block:
    - shell: initctl stop docker
      ignore_errors: true 
    - shell: initctl start docker
      ignore_errors: true
    - shell: initctl status docker
      register: result
    - debug:
        msg: "{{result.stdout}}"