---
- hosts: "k8s-nodes"
  vars_files:
  - "../config/config.yml"
  tasks:
  - name: "mkdir /var/lib/kubelet"
    file:
      path: "/var/lib/kubelet"
      state: directory
  - name: "copy files to nodes"
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0755
    with_items:
    - src: "../sbin/kubelet"
      dest: "/usr/bin/"
    - src: "../sbin/kube-proxy"
      dest: "/usr/bin/"
    - src: "template/k8s/kubelet.service"
      dest: "/lib/systemd/system/"
    - src: "template/k8s/kube-proxy.service"
      dest: "/lib/systemd/system/"
  - name: "template files to nodes"
    template:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
    with_items:
    - src: "template/k8s/config"
      dest: "/etc/kubernetes/"
    - src: "template/k8s/proxy"
      dest: "/etc/kubernetes/"
    - src: "template/k8s/kubelet"
      dest: "/etc/kubernetes/"
  - shell: "swapoff -a"
  - block:
    - shell: systemctl daemon-reload
    - service: 
        name: kubelet
        enabled: yes
    - service: 
        name: kubelet
        state: restarted
    - shell: systemctl status kubelet
      register: result
    - debug:
        msg: "{{result.stdout}}"
  - block:
    - shell: systemctl daemon-reload
    - service: 
        name: kube-proxy
        enabled: yes
    - service: 
        name: kube-proxy
        state: restarted
    - shell: systemctl status kube-proxy
      register: result
    - debug:
        msg: "{{result.stdout}}"
  