# 配置calico虚拟网络
---
- hosts: "k8s-all"
  vars_files:
  - "../config/config.yml"
  tasks:
  - name: "mkdir /etc/cni/net.d"
    file:
      path: "/etc/cni/net.d"
      state: directory
    when: k8s.network == "calico"
  - name: "copy files to all nodes"
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0755
    when: k8s.network == "calico"
    with_items:
    - src: "../sbin/calico"
      dest: "/usr/bin/"
    - src: "../sbin/calico-ipam"
      dest: "/usr/bin/"
    - src: "../sbin/loopback"
      dest: "/usr/bin/"
    - src: "../sbin/calicoctl"
      dest: "/usr/bin/"
  - name: "template files to all nodes"
    template:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
    when: k8s.network == "calico"
    with_items:
    - src: "template/calico/10-calico.conf"
      dest: "/etc/cni/net.d/"
    - src: "template/calico/calico-node.service"
      dest: "/lib/systemd/system/"
  - block:
    - shell: systemctl daemon-reload
    - service: 
        name: calico-node
        enabled: yes
    - service: 
        name: calico-node
        state: restarted
    - shell: systemctl status calico-node
      register: result
    - debug:
        msg: "{{result.stdout}}"
    when: k8s.network == "calico"