---
- hosts: "k8s-nodes"
  vars_files:
  - "../config/config.yml"
  tasks:
  - name: "mkdir /etc/cni/net.d"
    file:
      path: "/etc/cni/net.d"
      state: directory
    when: k8s.network == "calico"
  - name: "copy files to all nodes"
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0755
    when: k8s.network == "calico"
    with_items:
    - src: "../sbin/bridge"
      dest: "/usr/local/bin/"
    - src: "../sbin/host-local"
      dest: "/usr/local/bin/"
    - src: "../sbin/loopback"
      dest: "/usr/local/bin/"
    - src: "../sbin/calicoctl"
      dest: "/usr/local/bin/"
  - name: "template files to all nodes"
    template:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
    when: k8s.network == "calico"
    with_items:
    - src: "template/calico/10-default.conf"
      dest: "/etc/cni/net.d/"