# 安装etcd集群
---
- hosts: "etcd"
  vars_files:
  - "../config/config.yml"
  tasks:
  - name: "mkdir /var/lib/etcd"
    file:
      path: "/var/lib/etcd"
      state: directory
  - name: "mkdir /etc/etcd"
    file:
      path: "/etc/etcd"
      state: directory
  - name: "copy files to etcd cluster"
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0755
    with_items:
    - src: "../sbin/etcd"
      dest: "/usr/bin/"
    - src: "../sbin/etcdctl"
      dest: "/usr/bin/"
    - src: "template/etcd/etcd.service"
      dest: "/etc/init/etcd.conf"
  - name: "template files to etcd cluster"
    template:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
    with_items:
    - src: "template/etcd/etcd.conf"
      dest: "/etc/etcd/"
    - src: "template/ssl/etcd-csr.json"
      dest: "/etc/kubernetes/ssl/"
  - name: "create etcd.pem and etcd-key.pem"
    shell: "cd /etc/kubernetes/ssl/ && cfssl gencert \
            -ca=ca.pem \
            -ca-key=ca-key.pem \
            -config=ca-config.json \
            -profile=kubernetes etcd-csr.json | cfssljson -bare etcd"
  - block:
    - shell: initctl stop etcd
      ignore_errors: true 
    - shell: initctl start etcd
      ignore_errors: true
    - shell: initctl status etcd
      register: result
    - debug:
        msg: "{{result.stdout}}"