---
- hosts: "k8s-masters"
  vars_files:
  - "../config/config.yml"
  tasks:
  - name: "copy files to masters"
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0755
    with_items:
    - src: "../sbin/kube-apiserver"
      dest: "/usr/bin/"
    - src: "../sbin/kube-controller-manager"
      dest: "/usr/bin/"
    - src: "../sbin/kube-scheduler"
      dest: "/usr/bin/"
    - src: "template/k8s/kube-apiserver.service"
      dest: "/etc/init/kube-apiserver.conf"
    - src: "template/k8s/kube-controller-manager.service"
      dest: "/etc/init/kube-controller-manager.conf"
    - src: "template/k8s/kube-scheduler.service"
      dest: "/etc/init/kube-scheduler.conf"
    - src: "template/k8s/basic.csv"
      dest: "/etc/kubernetes/"
    - src: "template/k8s/token.csv"
      dest: "/etc/kubernetes/"
  - name: "template files to masters"
    template:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
    with_items:
    - src: "template/k8s/config"
      dest: "/etc/kubernetes/"
    - src: "template/k8s/apiserver"
      dest: "/etc/kubernetes/"
    - src: "template/k8s/controller-manager"
      dest: "/etc/kubernetes/"
    - src: "template/k8s/scheduler"
      dest: "/etc/kubernetes/"
    - src: "template/ssl/kubernetes-csr.json"
      dest: "/etc/kubernetes/ssl/"
  - name: "create kubernetes.pem and kubernetes-key.pem"
    shell: "cd /etc/kubernetes/ssl/ && cfssl gencert \
            -ca=ca.pem \
            -ca-key=ca-key.pem \
            -config=ca-config.json \
            -profile=kubernetes kubernetes-csr.json | cfssljson -bare kubernetes"
  - block:
    - shell: initctl stop kube-apiserver
      ignore_errors: true 
    - shell: initctl start kube-apiserver
      ignore_errors: true
    - shell: initctl status kube-apiserver
      register: result
    - debug:
        msg: "{{result.stdout}}"
  - block:
    - shell: initctl stop kube-controller-manager
      ignore_errors: true 
    - shell: initctl start kube-controller-manager
      ignore_errors: true
    - shell: initctl status kube-controller-manager
      register: result
    - debug:
        msg: "{{result.stdout}}"
  - block:
    - shell: initctl stop kube-scheduler
      ignore_errors: true 
    - shell: initctl start kube-scheduler
      ignore_errors: true
    - shell: initctl status kube-scheduler
      register: result
    - debug:
        msg: "{{result.stdout}}"
