# 卸载docker
---
- hosts: "k8s-all"
  vars_files:
  - "../config/config.yml"
  tasks:
  - service: 
      name: docker
      state: stopped
    ignore_errors: true 
  - service: 
      name: docker
      enabled: no
    ignore_errors: true 
  - shell: dpkg -r docker-ce
    ignore_errors: true 
  - shell: dpkg -r libltdl7
    ignore_errors: true 
  - shell: dpkg -r conntrack
    ignore_errors: true 
  - shell: rm -rf /var/log/containers
  - shell: rm -rf /opt/docker-ce_17.03.2-ce-0-ubuntu-xenial_amd64.deb
  - shell: rm -rf /opt/libltdl7_2.4.6-0.1_amd64.deb
  - shell: rm -rf /opt/conntrack_1.4.3-3_amd64.deb
  - shell: rm -rf /etc/docker && rm -rf /var/lib/docker
  - shell: dpkg -l | grep ^rc | cut -d' ' -f3 | xargs dpkg --purge
    ignore_errors: true 