# 卸载nodes
---
- hosts: "k8s-nodes"
  vars_files:
  - "../config/config.yml"
  tasks:
  - service: 
      name: kube-proxy
      state: stopped
    ignore_errors: true 
  - service: 
      name: kube-proxy
      enabled: no
    ignore_errors: true 
  - service: 
      name: kubelet
      state: stopped
    ignore_errors: true 
  - service: 
      name: kubelet
      enabled: no
    ignore_errors: true 
  #- service: 
  #    name: docker
  #    state: stopped
  #  ignore_errors: true 
  #- service: 
  #    name: docker
  #    enabled: no
  #  ignore_errors: true 
  #- shell: dpkg -r docker-ce
  #  ignore_errors: true 
  #- shell: dpkg -r libltdl7
  #  ignore_errors: true 
  - shell: rm -rf /var/log/kubernetes
  - shell: rm -rf /var/lib/kubelet
  - shell: rm -rf /etc/kubernetes
  - shell: rm -rf /usr/bin/kube-proxy
  - shell: rm -rf /usr/bin/kubelet
  - shell: rm -rf /usr/bin/kubectl
  - shell: rm -rf /opt/docker-ce_17.03.2-ce-0-ubuntu-xenial_amd64.deb
  - shell: rm -rf /opt/libltdl7_2.4.6-0.1_amd64.deb
  - shell: rm -rf /lib/systemd/system/kube-proxy.service
  - shell: rm -rf /lib/systemd/system/kubelet.service
  #- shell: rm -rf /etc/docker && rm -rf /var/lib/docker
  - shell: dpkg -l | grep ^rc | cut -d' ' -f3 | xargs dpkg --purge
    ignore_errors: true 