---
- hosts: "k8s-masters"
  vars_files:
  - "../config/config.yml"
  tasks:
  - shell: stop kube-scheduler
    ignore_errors: true  
  - shell: stop kube-controller-manager
    ignore_errors: true 
  - shell: stop kube-apiserver
    ignore_errors: true 
  - shell: rm -rf /etc/kubernetes
  - shell: rm -rf /usr/bin/kube-apiserver
  - shell: rm -rf /usr/bin/kube-controller-manager
  - shell: rm -rf /usr/bin/kube-scheduler
  - shell: rm -rf /usr/bin/kubectl
  - shell: rm -rf /etc/init/kube-apiserver.conf
  - shell: rm -rf /etc/init/kube-controller-manager.conf
  - shell: rm -rf /etc/init/kube-scheduler.conf